<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="11276" started-at="2017-08-23T15:41:30Z" finished-at="2017-08-23T15:41:41Z">
    <groups>
    </groups>
    <test name="JavaTutorial" duration-ms="11276" started-at="2017-08-23T15:41:30Z" finished-at="2017-08-23T15:41:41Z">
      <class name="TestNG2.TestNG_ScreenshotsOnFailTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestNG2.TestNG_ScreenshotsOnFailTest@2133c8f8]" name="setUp" is-config="true" duration-ms="4634" started-at="2017-08-23T10:41:30Z" finished-at="2017-08-23T10:41:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test1_invalidCredentials()[pri:0, instance:TestNG2.TestNG_ScreenshotsOnFailTest@2133c8f8]" name="test1_invalidCredentials" duration-ms="5850" started-at="2017-08-23T10:41:34Z" finished-at="2017-08-23T10:41:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestNG2.TestNG_ScreenshotsOnFailTest.test1_invalidCredentials(TestNG_ScreenshotsOnFailTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1_invalidCredentials -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestNG2.TestNG_ScreenshotsOnFailTest@2133c8f8]" name="tearDown" is-config="true" duration-ms="775" started-at="2017-08-23T10:41:40Z" finished-at="2017-08-23T10:41:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test1_invalidCredentials status=FAILURE method=TestNG_ScreenshotsOnFailTest.test1_invalidCredentials()[pri:0, instance:TestNG2.TestNG_ScreenshotsOnFailTest@2133c8f8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestNG2.TestNG_ScreenshotsOnFailTest -->
    </test> <!-- JavaTutorial -->
  </suite> <!-- Default Suite -->
</testng-results>
